### Numpy Library

- Processing N-Dimensional arrays

In [4]:
import numpy as np

li = [1,2,3,'z']

a = np.array(li)
#a

b = np.arange(15)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
rn = np.random.randint(0,100,size=10)
rn


array([36, 52, 55, 71, 17, 73,  9, 84, 30, 22])

In [7]:
m3 = np.random.randint(0,3,size=(3,3))
m3


array([[1, 1, 1],
       [2, 2, 0],
       [2, 0, 0]])

In [25]:
m3 = np.random.randint(0,3,size=(3,3,3))
print(m3)
print(m3.ndim)
print(m3.size)
print(m3.shape)
print(m3.dtype)
print(m3.itemsize)

[[[1 1 1]
  [1 1 0]
  [2 0 1]]

 [[2 0 0]
  [0 2 2]
  [1 1 2]]

 [[0 1 1]
  [1 2 1]
  [1 0 1]]]
3
27
(3, 3, 3)
int32
4


In [23]:
m3[:2,:3]

array([[[0, 1, 2],
        [0, 2, 1],
        [1, 1, 2]],

       [[0, 1, 1],
        [1, 2, 2],
        [1, 0, 0]]])

In [26]:
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [29]:
b.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [30]:
import numpy
numpy.__version__

'1.16.2'

In [31]:
import numpy as np
M = np.ones((3,3))
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

 ### Pandas
 
- Data Analysis
- Data Transformation
- Data Analysis

#### Notations

- Series
- DataFrames

In [40]:
import pandas as pd
internal1 = {'s1':21,'s2':18,'s3':24}

internal1 = pd.Series(internal1)

#internal1
internal2 = {'s1':11,'s2':12,'s3':24}
internal2 = pd.Series(internal2)
internal2

s1    11
s2    12
s3    24
dtype: int64

In [41]:
final = {'Internal1':internal1, 'Internal2':internal2}

final = pd.DataFrame(final)
final

Internal1  Internal2
s1         21         11
s2         18         12
s3         24         24

In [42]:
final = {'Internal1':internal1, 'Internal2':internal2}

final = pd.DataFrame(final)
final['Internal1']

s1    21
s2    18
s3    24
Name: Internal1, dtype: int64

In [43]:
final.columns #Lists of all columns

Index(['Internal1', 'Internal2'], dtype='object')

In [44]:
final.values # Lists of all rows

array([[21, 11],
       [18, 12],
       [24, 24]], dtype=int64)

In [46]:
final.values[2]

array([24, 24], dtype=int64)

In [48]:
final.values[2,0]

24

In [49]:
final.values[2][0]

24

In [51]:
for row in final.values:
    print('Internal1 - ', row[0] ,', Internal2 - ',row[1])

Internal1 -  21 , Internal2 -  11
Internal1 -  18 , Internal2 -  12
Internal1 -  24 , Internal2 -  24


In [58]:
final.loc[3] = [15,18]
final

Internal1  Internal2
s1         21         11
s2         18         12
s3         24         24
3          15         18

In [60]:
final.drop(3)

Internal1  Internal2
s1         21         11
s2         18         12
s3         24         24

In [63]:
final.values[1] = [12,18]
final

Internal1  Internal2
s1         21         11
s2         12         18
s3         24         24
3          15         18

In [65]:
## Reading csv file data
import pandas as pd
filepath = 'Data files/income.csv'
incomedf =  pd.read_csv(filepath)
incomedf

GEOID  State\t2005          2006   2007   2008   2009   2010  \
04000US01     Alabama        37150         37952  42212  44476  39980  40933   
04000US02      Alaska        55891  56418\t62993  63989  61604  57848  57431   
04000US04     Arizona        45245         46657  47215  46914  45739  46896   
04000US05    Arkansas        36658         37057  40795  39586  36538  38587   
04000US06  California        51755         55319  55734  57014  56134  54283   

            2011   2012     2013  
04000US01  42590  43464  41381.0  
04000US02  63648  61137      NaN  
04000US04  48621  47044  50602.0  
04000US05  41302  39018  39919.0  
04000US06  53367  57020  57528.0

In [74]:
# Extract income of all states in 2013

# California : 57528

for row in incomedf.values:
    print(row[0], ':', row[-1])

Alabama : 41381.0
Alaska : nan
Arizona : 50602.0
Arkansas : 39919.0
California : 57528.0


In [78]:
## Average income of particular state(Arizona)

sum = 0
for i in range(1,10):
    sum +=incomedf.values[1][i]
sum/len(incomedf.values[2][2:])

TypeError: unsupported operand type(s) for +=: 'int' and 'str'

In [81]:
## Average income of all states in 2012

sum = 0
for row in incomedf.values:
    sum += row[-3]
sum/len(incomedf.values)

49905.6